# Generated by Django 6.0.2 on 2026-02-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete - hidden from UI but kept in database'),
        ),
    ]
