# Generated by Django 6.0.2 on 2026-02-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_add_email_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default domain selected in dropdown (only one domain can be default)'),
        ),
    ]
